version: '4.28.0'
services:

  database_l:
    image: 803_database
    container_name: 803_database
    ports:
      - "3306:3306"
    volumes:
      - ./data:/803_database/data
    #command: mysqld --init-file="/803_database/data/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: projet_803_password
      #MYSQL_DATABASE: projet_803
      MYSQL_USER: projet_803
      MYSQL_PASSWORD: projet_803_password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  web_api_l:
    image: 803_web_api
    container_name: 803_web_api
    restart: on-failure:10
    ports:
      - "5000:5000"
    volumes:
      - ./code_web_api:/app
    depends_on:
      database_l:
        condition: service_healthy
        restart: true
    command: python /app/main.py database_l web_api projet_803_password 5000

  web_front_l:
    image: 803_web_front
    container_name: 803_web_front
    ports:
      - "80:80"
    volumes:
      - ./code_web_front:/app
    depends_on:
      - database_l
      - web_api_l
    command: python /app/main.py web_api_l 5000

